# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = '$shell$all'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[shell]
disabled = false
fish_indicator = ''

